#!/usr/bin/env bash
# Render the CI files from harness.config.yaml + the adapter + the deploy modules.
#
# The pipeline is described ONCE (config) and rendered per platform, so moving
# from GitHub to GitLab is a re-render, not a rewrite. Every generated file is
# committed and checked for drift, same discipline as harness-sync.
#
#   scripts/ci-gen.sh          # write the files
#   scripts/ci-gen.sh --check  # fail if any generated file has drifted
. "$(dirname "$0")/lib.sh"
load_adapter

CHECK=0; [ "${1:-}" = "--check" ] && CHECK=1
OUT="$HARNESS_ROOT"
if [ "$CHECK" = 1 ]; then OUT=$(mktemp -d); trap 'rm -rf "$OUT"' EXIT; mkdir -p "$OUT/.github/workflows"; fi

PLATFORMS=$(cfg ci.platforms '[github]' | tr -d '[]"' | tr ',' ' ')
RUNNER=$(cfg ci.runner ubuntu-latest)
MAIN=$(cfg git.main_branch main)
DEPLOY_ON=$(cfg deploy.enabled false)

# Pinned to commit SHAs, not tags. Refresh with `make pin-actions`.
A_CHECKOUT='actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7'

env_list() {  # names of configured deploy environments, in order
  awk '
    /^deploy:/ {inD=1; next}
    /^[^[:space:]#]/ {inD=0}
    inD && /^[[:space:]]+environments:/ {inE=1; next}
    inE && /^[[:space:]]*-[[:space:]]*name:/ { n=$0; sub(/.*name:[[:space:]]*/,"",n); gsub(/[[:space:]]/,"",n); print n }
  ' "$CONFIG"
}
env_field() {  # env_field <env> <key>
  E="$1" K="$2" awk '
    /^deploy:/ {inD=1; next}
    /^[^[:space:]#]/ {inD=0}
    inD && /^[[:space:]]+environments:/ {inE=1; next}
    inE && /^[[:space:]]*-[[:space:]]*name:/ { cur=$0; sub(/.*name:[[:space:]]*/,"",cur); gsub(/[[:space:]]/,"",cur); next }
    inE && cur==ENVIRON["E"] && $0 ~ "^[[:space:]]*"ENVIRON["K"]":" {
      v=$0; sub(/^[^:]*:[[:space:]]*/,"",v); sub(/[[:space:]]+#.*$/,"",v); gsub(/[[:space:]]*$/,"",v); print v; exit
    }
  ' "$CONFIG"
}

# ---------------------------------------------------------------- GitHub -----
gen_github() {
  mkdir -p "$OUT/.github/workflows"

  # --- gates.yml : the deterministic + toolchain jobs ---
  {
    cat <<YAML
name: gates
# GENERATED by scripts/ci-gen.sh from harness.config.yaml. Run 'make ci-gen'
# after changing the pipeline; CI fails if this file drifts from the config.
#
# Deterministic gates run first and need no toolchain, so a malformed change
# fails in seconds instead of after a dependency install.

on:
  pull_request:
  push:
    branches: [$MAIN]

# Least privilege. A job needing more grants it on itself, visibly in the diff.
permissions:
  contents: read

concurrency:
  group: gates-\${{ github.workflow }}-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  deterministic:
    runs-on: $RUNNER
    steps:
      - uses: $A_CHECKOUT
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Instruction budgets
        run: ./scripts/gates/instruction-budget.sh
      - name: Rule coverage
        run: ./scripts/gates/rule-coverage.sh
      - name: Secret scan
        run: ./scripts/gates/secret-scan.sh
      - name: Supply chain
        run: ./scripts/gates/supply-chain.sh
      - name: Vendored skills
        run: ./scripts/gates/skills-integrity.sh
      - name: skill namespace
        run: ./scripts/gates/skill-namespace.sh
      - name: Requirement register
        run: ./scripts/gates/requirements.sh
      - name: Invariant register
        run: ./scripts/gates/invariants.sh
      - name: Learning loop
        run: ./scripts/gates/learning.sh
      - name: API proposals — status per operation
        run: ./scripts/gates/api-contract.sh
      - name: API agreements — no silent drift
        run: ./scripts/gates/api-agreements.sh
      - name: Spec clarity
        run: ./scripts/gates/spec-clarity.sh
      - name: Design-token drift
        run: ./scripts/gates/design-tokens.sh
      - name: Design-system coherence
        run: ./scripts/gates/design-system.sh
      - name: Branch hygiene
        run: ./scripts/gates/branch-hygiene.sh
      - name: Surface policy
        run: ./scripts/gates/policy.sh "origin/\${{ github.base_ref || '$MAIN' }}"
      - name: Gates reject what they exist to reject
        run: ./scripts/gate-selftest.sh
      - name: Generated files in sync
        run: ./scripts/harness-sync.sh --check && ./scripts/ci-gen.sh --check
      - name: Harness intact
        run: ./scripts/verify-harness.sh --level 2
      - name: Harness not modified alongside product code
        env:
          PR_BODY: \${{ github.event.pull_request.body }}
        run: ./scripts/gates/protected-paths.sh "origin/\${{ github.base_ref || '$MAIN' }}"

  toolchain:
    runs-on: $RUNNER
    steps:
      - uses: $A_CHECKOUT
        with:
          persist-credentials: false
YAML
    ci_setup github
    cat <<'YAML'
      - run: make deps
      - run: make lint
      - run: make format-check
      - run: make typecheck
      - run: make test
YAML
    cat <<YAML

  pr-contract:
    if: github.event_name == 'pull_request'
    runs-on: $RUNNER
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: $A_CHECKOUT
        with:
          persist-credentials: false
      - name: PR description must carry verification evidence
        env:
          BODY: \${{ github.event.pull_request.body }}
        run: ./scripts/ci/pr-body.sh
YAML
  } > "$OUT/.github/workflows/gates.yml"

  # --- deploy.yml : one job per configured environment ---
  [ "$DEPLOY_ON" = "true" ] || { rm -f "$OUT/.github/workflows/deploy.yml"; return; }
  {
    cat <<YAML
name: deploy
# GENERATED by scripts/ci-gen.sh. Edit harness.config.yaml, then 'make ci-gen'.
#
# Deploy runs only after gates pass. Production references a GitHub
# \`environment:\`, whose required reviewers are configured in repo settings —
# that gate CANNOT be expressed in YAML and nothing here can verify it.

on:
  workflow_run:
    workflows: [gates]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read

jobs:
YAML
    for e in $(env_list); do
      local targets
      targets=$(env_field "$e" targets | tr -d '[]"' )
      [ "$targets" = "none" ] && continue
      cat <<YAML
  $e:
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch'
    runs-on: $RUNNER
    environment:
      name: $e
YAML
      # id-token is what makes keyless cloud auth possible. Without it there is
      # no OIDC token and the only alternative is a long-lived key.
      case "$targets" in
        *cloud-run*) cat <<'YAML'
    permissions:
      contents: read
      id-token: write
YAML
;;
        *) cat <<'YAML'
    permissions:
      contents: read
YAML
;;
      esac
      cat <<YAML
    steps:
      - uses: $A_CHECKOUT
        with:
          persist-credentials: false
YAML
      case "$targets" in
        *cloud-run*) cat <<'YAML'
      # Keyless. The pool MUST carry an attribute condition bound to
      # repository_id / repository_owner_id — a pool without one can be entered
      # by any repository on GitHub. Do not match on a name-parsed `sub`:
      # GitHub is moving to immutable ID-embedded subjects and name-based
      # matches break on the next rename or transfer.
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_DEPLOY_SA }}
YAML
;;
        *supabase*) cat <<'YAML'
      - uses: supabase/setup-cli@3c2f5e2ae34c34e428e8e206e2c4d21fa2d20fbf # v2.1.1
        with:
          version: 2.1.1
YAML
;;
      esac
      cat <<YAML
      - name: Plan
        env:
          DEPLOY_ENV: $e
        run: ./scripts/deploy.sh $e plan
      - name: Apply
        env:
          DEPLOY_ENV: $e
          DEPLOY_CONFIRM: '1'
        run: ./scripts/deploy.sh $e apply
YAML
      if [ "$(env_field "$e" staged_cutover)" = "true" ]; then
        cat <<YAML
      # Deploy and cutover are separate. Everything above is live-but-untrafficked;
      # promote is what actually exposes it. Keep them separate so the approval
      # gate has something to sit between.
      - name: Promote
        env:
          DEPLOY_ENV: $e
          DEPLOY_CONFIRM: '1'
        run: ./scripts/deploy.sh $e promote
YAML
      fi
      echo
    done
  } > "$OUT/.github/workflows/deploy.yml"
}

# ---------------------------------------------------------------- GitLab -----
gen_gitlab() {
  {
    cat <<YAML
# GENERATED by scripts/ci-gen.sh from harness.config.yaml. Run 'make ci-gen'.
# Same pipeline as .github/workflows/, rendered for GitLab.
stages: [gates, toolchain, deploy]

default:
YAML
    ci_setup gitlab
    cat <<'YAML'

.gates: &gates
  stage: gates
  script:
    - ./scripts/gates/instruction-budget.sh
    - ./scripts/gates/rule-coverage.sh
    - ./scripts/gates/secret-scan.sh
    - ./scripts/gates/supply-chain.sh
    - ./scripts/gates/spec-clarity.sh
    - ./scripts/gates/design-tokens.sh
    - ./scripts/gates/branch-hygiene.sh
    - ./scripts/gates/skill-namespace.sh
    - ./scripts/harness-sync.sh --check
    - ./scripts/ci-gen.sh --check
    - ./scripts/verify-harness.sh --level 2

deterministic:
  <<: *gates

toolchain:
  stage: toolchain
  script:
    - make deps
    - make lint
    - make format-check
    - make typecheck
    - make test
YAML
    [ "$DEPLOY_ON" = "true" ] || return 0
    for e in $(env_list); do
      local targets; targets=$(env_field "$e" targets | tr -d '[]"')
      [ "$targets" = "none" ] && continue
      cat <<YAML

deploy:$e:
  stage: deploy
  environment:
    name: $e
  variables:
    DEPLOY_ENV: $e
    DEPLOY_CONFIRM: '1'
  script:
    - ./scripts/deploy.sh $e plan
    - ./scripts/deploy.sh $e apply
YAML
      [ "$(env_field "$e" approval)" = "true" ] && echo "  when: manual   # GitLab's protected-environment approval sits here"
    done
  } > "$OUT/.gitlab-ci.yml"
}

# --------------------------------------------------------------- Bitrise -----
gen_bitrise() {
  cat > "$OUT/bitrise.yml" <<YAML
# GENERATED by scripts/ci-gen.sh from harness.config.yaml. Run 'make ci-gen'.
# Mobile CI. Signing material lives in Bitrise's code-signing store and is never
# committed — the repo holds the shape of the config, never the values.
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

workflows:
  gates:
    steps:
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - script@1:
          title: Deterministic gates
          inputs:
            - content: |-
                #!/usr/bin/env bash
                set -euo pipefail
                ./scripts/gates/instruction-budget.sh
                ./scripts/gates/rule-coverage.sh
                ./scripts/gates/secret-scan.sh
                ./scripts/gates/supply-chain.sh
                ./scripts/harness-sync.sh --check
                ./scripts/ci-gen.sh --check
      - script@1:
          title: Toolchain
          inputs:
            - content: |-
                #!/usr/bin/env bash
                set -euo pipefail
                make deps && make lint && make format-check && make test

  release:
    steps:
      - activate-ssh-key@4: {}
      - git-clone@8: {}
      - script@1:
          title: Build
          inputs:
            - content: make build
      # Signing uses Bitrise-managed certificates. Never add key material here.
      - sign-apk@2: {}
      - deploy-to-bitrise-io@2:
          inputs:
            - is_enable_public_page: 'false'   # signed builds are not public URLs
            - notify_user_groups: none
YAML
}

for p in $PLATFORMS; do
  case "$p" in
    github)  gen_github ;;
    gitlab)  gen_gitlab ;;
    bitrise) gen_bitrise ;;
    *) warn "unknown ci platform '$p' — skipped" ;;
  esac
done

if [ "$CHECK" = 1 ]; then
  rc=0
  for rel in .github/workflows/gates.yml .github/workflows/deploy.yml .gitlab-ci.yml bitrise.yml; do
    if [ -f "$OUT/$rel" ]; then
      diff -q "$OUT/$rel" "$HARNESS_ROOT/$rel" >/dev/null 2>&1 || { warn "drifted: $rel"; rc=1; }
    elif [ -f "$HARNESS_ROOT/$rel" ]; then
      case "$rel" in *deploy.yml) warn "orphan: $rel (deploy is disabled in config)"; rc=1 ;; esac
    fi
  done
  [ "$rc" -eq 0 ] || fail "CI files are out of date — run 'make ci-gen'"
  ok "CI files in sync"
else
  ok "rendered CI for: $PLATFORMS"
  if [ "$DEPLOY_ON" = "true" ]; then
    for e in $(env_list); do
      [ "$(env_field "$e" approval)" = "true" ] || continue
      warn "ACTION REQUIRED (a human, once): configure required reviewers on the '$e' environment."
      warn "  GitHub: Settings → Environments → $e → Required reviewers."
      warn "  This gate cannot be expressed in YAML and nothing in this repo can verify it."
      warn "  Put deploy credentials in that ENVIRONMENT's secrets, not repo secrets —"
      warn "  environment secrets are unreadable until the protection rule passes."
    done
  fi
fi
