#!/usr/bin/env bash
# Generate the tool-specific instruction files from the canonical ones.
#
#   canonical                       generated
#   ─────────────────────────────   ──────────────────────────────────────────
#   AGENTS.md                    →  CLAUDE.md (import + Claude tail)
#                                →  .github/copilot-instructions.md
#   .agents/rules/<n>.md         →  .cursor/rules/<n>.mdc
#                                →  .github/instructions/<n>.instructions.md
#
# `--check` regenerates into a temp dir and diffs. That is the CI gate: one rule,
# one owner file, and no tool view allowed to drift away from it.
. "$(dirname "$0")/lib.sh"

CHECK=0; [ "${1:-}" = "--check" ] && CHECK=1
OUT="$HARNESS_ROOT"
if [ "$CHECK" = 1 ]; then OUT=$(mktemp -d); trap 'rm -rf "$OUT"' EXIT
  mkdir -p "$OUT/.cursor/rules" "$OUT/.github/instructions"
fi
TARGETS="$(cfg harness.targets '[claude, cursor, copilot]' | tr -d '[]" ')"
want() { printf '%s' ",$TARGETS," | grep -q ",$1," ; }

banner_md() { printf '<!-- GENERATED by scripts/harness-sync.sh from %s. Edit the source, then run `make harness-sync`. -->\n' "$1"; }

# --- CLAUDE.md : import + Claude-specific tail ---------------------------------
# The tail has its own canonical source file. It used to be read back out of the
# generated CLAUDE.md, which meant anything appended there was re-emitted on the
# next sync and was invisible to --check: a permanent, undetectable instruction
# channel. Generated files are outputs. They are never also inputs.
TAIL_SRC="$HARNESS_ROOT/.agents/claude-tail.md"
if want claude; then
  if [ ! -f "$TAIL_SRC" ]; then
    mkdir -p "$(dirname "$TAIL_SRC")"
    printf '%s\n' '<!-- HARNESS-SYNC:CLAUDE-TAIL -->' '## Claude Code specifics' '' 'No Claude-specific rules yet.' > "$TAIL_SRC"
    info "created .agents/claude-tail.md — edit that file, never CLAUDE.md"
  fi
  { banner_md "AGENTS.md + .agents/claude-tail.md"; echo '@AGENTS.md'; echo; cat "$TAIL_SRC"; } > "$OUT/CLAUDE.md"
fi

# --- Copilot repo instructions -------------------------------------------------
if want copilot; then
  mkdir -p "$OUT/.github/instructions"
  # Strip the authoring comment block; Copilot gets the rules only.
  { banner_md AGENTS.md; awk '/<!--/{c=1} !c{print} /-->/{c=0}' "$HARNESS_ROOT/AGENTS.md"; } > "$OUT/.github/copilot-instructions.md"
fi
[ "$(want cursor; echo $?)" = 0 ] && mkdir -p "$OUT/.cursor/rules"

# --- Path rules → Cursor .mdc and Copilot .instructions.md ---------------------
for f in "$HARNESS_ROOT"/.agents/rules/*.md; do
  [ -f "$f" ] || continue
  name=$(basename "$f" .md); [ "$name" = "README" ] && continue
  fm() { awk -v k="$1" 'f&&/^---/{exit} f&&$0~"^"k":"{sub("^"k":[[:space:]]*",""); print; exit} /^---/{f=1}' "$f"; }
  desc=$(fm description); globs=$(fm paths); trig=$(fm trigger)
  body=$(awk 'BEGIN{n=0} /^---/{n++; next} n>=2' "$f")
  globs_csv=$(printf '%s' "${globs:-}" | tr -d '[]"' | sed 's/, */,/g; s/^ *//; s/ *$//')

  if want cursor; then
    {
      echo '---'
      echo "description: ${desc:-$name}"
      [ -n "$globs_csv" ] && echo "globs: $globs_csv"
      if [ "${trig:-glob}" = "always" ]; then echo "alwaysApply: true"; else echo "alwaysApply: false"; fi
      echo '---'
      banner_md ".agents/rules/$name.md"
      printf '%s\n' "$body"
    } > "$OUT/.cursor/rules/$name.mdc"
  fi

  if want copilot; then
    {
      echo '---'
      [ -n "$globs_csv" ] && echo "applyTo: \"$globs_csv\"" || echo 'applyTo: "**"'
      echo '---'
      banner_md ".agents/rules/$name.md"
      printf '%s\n' "$body"
    } > "$OUT/.github/instructions/$name.instructions.md"
  fi
done

if [ "$CHECK" = 1 ]; then
  rc=0
  for rel in CLAUDE.md .github/copilot-instructions.md; do
    [ -f "$OUT/$rel" ] || continue
    if ! diff -q "$OUT/$rel" "$HARNESS_ROOT/$rel" >/dev/null 2>&1; then warn "drifted: $rel"; rc=1; fi
  done
  for g in "$OUT"/.cursor/rules/*.mdc "$OUT"/.github/instructions/*.instructions.md; do
    [ -f "$g" ] || continue
    rel="${g#"$OUT"/}"
    if ! diff -q "$g" "$HARNESS_ROOT/$rel" >/dev/null 2>&1; then warn "drifted: $rel"; rc=1; fi
  done
  # Orphans, in both directions:
  #   (a) a generated file whose canonical rule was deleted
  #   (b) a generated file for a target that is no longer in harness.targets —
  #       switching a target off does not delete the file, and the tool that
  #       reads it does not know it was switched off.
  for g in "$HARNESS_ROOT"/.cursor/rules/*.mdc; do
    [ -f "$g" ] || continue
    n=$(basename "$g" .mdc)
    if ! want cursor; then warn "orphan: .cursor/rules/$n.mdc (cursor is not in harness.targets — Cursor still reads it)"; rc=1
    elif [ ! -f "$HARNESS_ROOT/.agents/rules/$n.md" ]; then warn "orphan: .cursor/rules/$n.mdc (no .agents/rules/$n.md)"; rc=1; fi
  done
  for g in "$HARNESS_ROOT"/.github/instructions/*.instructions.md; do
    [ -f "$g" ] || continue
    n=$(basename "$g" .instructions.md)
    if ! want copilot; then warn "orphan: .github/instructions/$n.instructions.md (copilot is not in harness.targets)"; rc=1
    elif [ ! -f "$HARNESS_ROOT/.agents/rules/$n.md" ]; then warn "orphan: .github/instructions/$n.instructions.md (no .agents/rules/$n.md)"; rc=1; fi
  done
  for pair in "claude:CLAUDE.md" "copilot:.github/copilot-instructions.md"; do
    t="${pair%%:*}"; rel="${pair#*:}"
    if ! want "$t" && [ -f "$HARNESS_ROOT/$rel" ]; then
      warn "orphan: $rel ($t is not in harness.targets — that tool still reads this file)"; rc=1
    fi
  done
  [ "$rc" -eq 0 ] || fail "generated tool files are out of date — run 'make harness-sync'"
  ok "tool files in sync"
else
  ok "generated tool views for: $TARGETS"
fi
