#!/usr/bin/env bash
# sync-skills.sh — make the harness's procedures invokable, without copying them.
#
# A procedure is canonical, host-agnostic, and carries harness metadata a skill
# file has no room for: which surface it belongs to, who owns it, whether it is
# live. But in that form NOTHING can invoke it — it is a document you have to
# know to open, which is how the ratchet quietly stops being run.
#
# So: generate a thin skill per procedure that POINTS at it. Same pattern the
# constitution already uses — AGENTS.md is canonical and CLAUDE.md is a
# one-line redirect. A redirect stays correct; a copy drifts, and nothing tells
# you which of the two the agent read.
#
#   --check   report drift and exit non-zero. Used by the gate.

# shellcheck source=lib.sh
. "$(dirname "$0")/lib.sh"
ROOT=$(harness_root "$(dirname "$0")") || exit 1
cd "$ROOT" || exit 1

CHECK=0
[ "${1-}" = "--check" ] && CHECK=1

fm() {  # fm FILE KEY — read one frontmatter value
  awk -v k="$2" '
    /^---[[:space:]]*$/ { n++; if (n==2) exit; next }
    n==1 { if (index($0, k ":") == 1) { sub("^" k ":[[:space:]]*", ""); print; exit } }
  ' "$1"
}

n_proc=0; n_written=0; n_drift=0
for p in procedures/*.md; do
  [ -f "$p" ] || continue
  case "$p" in */_TEMPLATE.md) continue ;; esac
  n_proc=$((n_proc + 1))

  id=$(fm "$p" id); desc=$(fm "$p" description); status=$(fm "$p" status)
  [ -n "$id" ]   || { fail "$p has no 'id:' — cannot generate a skill for it"; continue; }
  [ -n "$desc" ] || { fail "$p has no 'description:' — a host has nothing to match on"; continue; }
  [ "$status" = "retired" ] && continue

  out="$ROOT/.claude/skills/$id/SKILL.md"
  tmp=$(mktemp) || { fail "cannot create a temp file"; continue; }
  {
    printf -- '---\n'
    printf 'name: %s\n' "$id"
    printf 'description: %s\n' "$desc"
    printf -- '---\n\n'
    printf '<!-- GENERATED by scripts/sync-skills.sh from %s — do not edit.\n' "$p"
    printf '     Edit the procedure; this file is a pointer, not a copy. -->\n\n'
    printf '# %s\n\n' "$id"
    printf 'Read `%s` and follow it exactly. If the conversation has been compacted since you read it, read it again before the next step — a summary of a procedure is not the procedure.\n\n' "$p"
    printf 'It is the canonical version. Nothing here restates it, because two copies of a procedure drift and the agent obeys whichever it read last.\n'
  } > "$tmp"

  if [ -f "$out" ] && cmp -s "$tmp" "$out"; then
    rm -f "$tmp"; continue
  fi
  if [ "$CHECK" -eq 1 ]; then
    n_drift=$((n_drift + 1))
    fail "generated skill out of date: .claude/skills/$id/SKILL.md — run ./scripts/sync-skills.sh"
    rm -f "$tmp"
  else
    mkdir -p "$(dirname "$out")"; mv "$tmp" "$out"; n_written=$((n_written + 1))
  fi
done

# A skill whose procedure is gone is residue that still loads.
if [ -d .claude/skills ]; then
  for d in .claude/skills/*/; do
    [ -d "$d" ] || continue
    id=$(basename "$d")
    [ -f "procedures/$id.md" ] && continue
    if [ "$CHECK" -eq 1 ]; then
      fail "orphaned generated skill: $d has no procedures/$id.md"
      n_drift=$((n_drift + 1))
    else
      warn "orphaned generated skill: $d — its procedure is gone; delete it"
    fi
  done
fi

if [ "$CHECK" -eq 1 ]; then
  [ "$n_drift" -eq 0 ] && pass "generated skills match their procedures" "$n_proc procedure(s)"
else
  pass "skills synced" "$n_proc procedure(s), $n_written written"
fi
finish
